osx_image: xcode10.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/com.awareframework.ios.sensor.barometer.xcworkspace
  -scheme com.awareframework.ios.sensor.barometer-Example -sdk iphonesimulator12.1
  -destination OS=12.1,name="iPhone X" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
  -allowProvisioningUpdates | XCPRETTY
deploy:
  provider: script
  script: "./scripts/release.sh"
  on:
    tags: true
after_success:
- echo 'success!'
env:
  global:
  - secure: JNkm7b8PnFnEq7drRW5xplpF8tgmg/JvRQ7CVNmfMABOIrnXbtwOWp8NWWdXucWv+YloMZNPoZ1uJwpHm7knGyGaG4cYeZsXSplbfuFpXC6CuZZsXKFE/zr2xJtIhd6XDWLPJ16Lqhz+gstOpjaBuOJqVjQeWLnH9gJ4TYVZr34c2HMelO9guIn08YT+bsyMbHSbKhz8l8oWDhtYJil6TXJUMYCtMvB4ee6AcZ6oBneoxn1bp1J8VYs0Y6Tez2/yfS3W/2RIiVzectNWlB9ISrkNJImKRP2sctcKH9jCeGOE6YcHkgzHi9zHiP2DHIpp42sU4ZQO8GqbVpLI66gH8T0PXafqyKIG9y+p4BoQVUBP+LjDuwN6b33vIsg+aIU4a66k3Zu9M+4Mzxs9kyq+6mJ2KPUWyBPOTPaKFWia3H/fj7HDqeBwcAZVEISLpS6nZWONJTFL1eh6msuq6u/qDeFZMgBWmZHjP6oeVpAfs4eLAPXliuB+thCkJhenwgxX3eCqsD1mtnupHtiMEnNNtjebpJJraJZhBt2MAwW6IqQn5YiwCGzGnIN6pZaM1+3JGaRTJCCpKO6NekpRCqSHH8talyFa37HseEpJEUsAsvLCMEekm2+dMINqQ4opSUU9L8HZsvjuaqX4UOMKnWuHp7E51coW8DbH9jHlIBEP7wQ=
  - secure: RLHnYhEZcslb4tFAR3lqTmhFTI7ahXh55S+ARAiGo68ZgWaQhVMMHK9zJ99zsgCHiFJAj/AzaDDual8ew9bBZfgqkePmsbmlwW3lu7kSk8bnLp2T0DHvdypZXpN83rZsO6ufFKaUYxsc7Q49liHPsm8rrm/K3ZDFm5ZM9P20i2jDuSww1cCSr1yS4gxpQzrXMD8YBgE7dK4h9TT7AqGCzueEiFv6b48e7LBBGoQ8gIBBQV45tBenWERldrLaCOrLdhT1h1nF2YhvjAJoG9byFJsdz+T8Ot1ChO/xSJp+v4s65PeZkJTM/AxTLdiWGGX2ANjIhwyH7y2sTeMxqjyEttxapqfqCbSfeGcz+RaTjRoUVsenLf2t+siNrEwnKyu18cl+/yWw+uvXOTI3Xg5mLiS2a3dEQlGOOMYgm0WEi2BEyUQFdEcLLLImFIofnc5Cjbn43z3xLqXlTibXZuVp0mPQSUxQI4C5yKKEo9O/nB8vTR3JLpDimDQNOmnNAAoWuFBZYSFFYMquswacCUXK/E+lPWFWwdTMp8TtB/1/Rb1I4WcEnpewxObcO2G4gduiRPWBr0Few0ug5USvHhP9dpMgFhndk5Y0IN8Q2o+rhMARPBGD7Vm+yTJFSjeppf4cOiIGpr0SpoIwMGFm+1KwAWeU/tj7bErNmsmvL/RjpqA=
notifications:
  slack:
    secure: JoJkTCJ9JAoWsdhgbHD7WteoH5LpsWFXL2izLRVPZ/uG2Xc30hRq68YMJr+6QUDj3JxL4pD/2a+BR9lxaLDvnGgc2FWS3Vpff6CX/4079D0DgjsjwgBeymsldh0V00TP0jR+N113xiAJ9yMiKbBp6M/A3aRczVHbDFPVTXZ48bKxr4HlbMbiK/szj4LxByham+DxhcsBPHtYdGX5lMRasKmTRajJXfRrKBXFa1pAYIJvXoYdvRk+x+OApILoXTUY7gLa6oXLnicew7S8Lx+Larc7VMnVKlJKv/EYFH+nNA8S4Fz2C8dlV1+f8g0J/VVk5Alx40xF9Q8paZ12VF1ZRBfVe0DcCApnTwbyuLqT5q+5nWAVF+AYHzXbEDygAVQOJbIj3TCt1nY1ieNtjblXb5Em0PXQAu296TIdfmVKX779w3t6F9P52jU2EDvTo7GYmYD+dd7hPBIUR5X5LDUUyQxt48mxBr1/XzI5TCJiuQydpsXxYDM0HyS0PO9lZ8fwVgh40snJ4nzhyYNoAtZSn8/V1hd3UY9NLYD/nCfxWYHDQtMQ85wMTW6UCcUPEeDlvjViyjoapxwBF3lznomCOLN8wEGRYakCW+eJZNFFdwbcmCfHEeKTKqlUvALbUQWATkU75HCLgW84ONjzS3ZjFaHImbBc7r/DjtGfkSd2FZ0=
